# Generated by Django 4.0.2 on 2022-06-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_floors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='SQFT_Living',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_above',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_basement',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_living15',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_lot15',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='yr_renovated',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
