# Generated by Django 4.0.2 on 2022-06-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_property_sqft_living_alter_property_sqft_above_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
