# Generated by Django 4.0.2 on 2022-06-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_property_bedrooms_alter_property_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
