# Generated by Django 4.0.2 on 2022-06-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_alter_property_bedrooms_alter_property_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='grade',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='long',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='waterfront',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='yr_built',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_lot15',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='view',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
