# Generated by Django 4.0.2 on 2022-06-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_grade_property_long_property_waterfront_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
