# Generated by Django 4.0.2 on 2022-06-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_property_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property'},
        ),
    ]
