# Generated by Django 4.0.2 on 2022-06-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_alter_property_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='SQFT_Living',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_above',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_basement',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_living15',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='yr_renovated',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
