# Generated by Django 4.0.2 on 2022-06-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_alter_property_sqft_living_alter_property_sqft_above_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='SQFT_Living',
        ),
        migrations.RemoveField(
            model_name='property',
            name='SQFT_above',
        ),
        migrations.RemoveField(
            model_name='property',
            name='SQFT_basement',
        ),
        migrations.RemoveField(
            model_name='property',
            name='SQFT_living15',
        ),
        migrations.RemoveField(
            model_name='property',
            name='SQFT_lot',
        ),
        migrations.RemoveField(
            model_name='property',
            name='SQFT_lot15',
        ),
        migrations.RemoveField(
            model_name='property',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='property',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='property',
            name='long',
        ),
        migrations.RemoveField(
            model_name='property',
            name='view',
        ),
        migrations.RemoveField(
            model_name='property',
            name='waterfront',
        ),
        migrations.RemoveField(
            model_name='property',
            name='yr_built',
        ),
        migrations.RemoveField(
            model_name='property',
            name='yr_renovated',
        ),
        migrations.RemoveField(
            model_name='property',
            name='zip_code',
        ),
    ]
