# Generated by Django 4.0.2 on 2022-06-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_property_sqft_living_property_sqft_above_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='SQFT_Living',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_above',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_basement',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_living15',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_lot',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='SQFT_lot15',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='condition',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='long',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='view',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='waterfront',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='yr_built',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='yr_renovated',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
