# Generated by Django 4.0.2 on 2022-06-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_alter_property_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='long',
            field=models.DecimalField(decimal_places=4, max_digits=7, null=True),
        ),
    ]
