# Generated by Django 4.0.2 on 2022-06-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_alter_property_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='long',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
    ]
