# Generated by Django 4.0.2 on 2022-06-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_alter_property_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='long',
        ),
    ]
