# Generated by Django 4.0.2 on 2022-06-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0027_remove_property_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='long',
            field=models.DecimalField(blank=0, decimal_places=3, max_digits=5, null=True),
        ),
    ]
