# Generated by Django 4.0.2 on 2022-06-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_property_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='long',
            field=models.DecimalField(blank=0, decimal_places=10, max_digits=11, null=True),
        ),
    ]
