# Generated by Django 4.0.2 on 2022-06-15 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_alter_property_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='long',
            field=models.DecimalField(blank=0, decimal_places=7, max_digits=11, null=True),
        ),
    ]
