# Generated by Django 4.0.2 on 2022-06-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0031_alter_property_long_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='long',
            field=models.DecimalField(blank=0, decimal_places=7, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=7, max_digits=13, null=True),
        ),
    ]
