# Generated by Django 4.0.2 on 2022-06-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_alter_property_bathrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(blank=0, decimal_places=3, max_digits=5, null=True),
        ),
    ]
