# Generated by Django 4.0.2 on 2022-06-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(blank=0, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.DecimalField(blank=0, decimal_places=2, max_digits=5, null=True),
        ),
    ]
