# Generated by Django 4.0.2 on 2022-06-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_property_user_uploadedprob_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedprob',
            name='user',
        ),
    ]
