# Generated by Django 4.0.2 on 2022-06-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0040_remove_uploadedprob_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
    ]
