# Generated by Django 4.0.2 on 2022-06-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0041_remove_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedprob',
            name='images',
        ),
    ]
