# Generated by Django 4.0.2 on 2022-06-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0042_remove_uploadedprob_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['price']},
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
