# Generated by Django 4.0.2 on 2022-06-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0043_alter_property_options_property_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propimage',
            old_name='Property',
            new_name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
