# Generated by Django 4.0.2 on 2022-06-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_rename_property_propimage_property_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
    ]
