# Generated by Django 4.0.2 on 2022-06-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0045_alter_property_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedprob',
            name='images',
            field=models.ImageField(null=True, upload_to='new_photos/%y/%m/%d'),
        ),
    ]
