# Generated by Django 4.0.2 on 2022-06-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0046_uploadedprob_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedprob',
            name='prop_kind',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedprob',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedprob',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedprob',
            name='location',
            field=models.URLField(null=True),
        ),
    ]
