# Generated by Django 4.0.2 on 2022-06-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0047_uploadedprob_prop_kind_alter_uploadedprob_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedprob',
            name='images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uploadedprob',
            name='videos',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
