# Generated by Django 4.0.2 on 2022-06-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Personal_Info',
        ),
    ]
