# Generated by Django 4.0.2 on 2022-06-21 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_personal_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
